language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.4
  - 1.5
  - nightly

notifications:
  email:
    if: type = pull_request

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      env:
        - GKSwstype=nul
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

coveralls: true
