language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("SeisModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
