name = "SeisModels"
uuid = "47bbc3d6-959e-5592-a00a-d17660d07a0f"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]
version = "0.3.2"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
